# Generated by Django 4.2 on 2023-06-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='userRol_id',
            new_name='UsRol_id',
        ),
        migrations.RenameField(
            model_name='evaluacion',
            old_name='eva_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='labor',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='labor',
            old_name='lab_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='periodo',
            old_name='per_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='rol',
            old_name='rol_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='tipolabor',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='tipolabor',
            old_name='tl_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userrol',
            old_name='userRol_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userrol',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='eva_estado',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='eva_puntaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='labor',
            name='horas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol_descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
