# Generated by Django 4.2 on 2023-06-14 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_userrol_id_evaluacion_usrol_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='UsRol_id',
            new_name='userRol_id',
        ),
        migrations.RenameField(
            model_name='userrol',
            old_name='rol_id',
            new_name='rol',
        ),
        migrations.RenameField(
            model_name='userrol',
            old_name='user_id',
            new_name='user',
        ),
    ]
